### PR TITLE
Fixed assetic dump command

### PR DESCRIPTION
**Pull request by ghost**
`assetic:watch` command was not working.

The cause is that `Symfony\Bundle\AsseticBundle\Factory\AssetFactory` was creating `Assetic\Asset\AssetReference` object Instead of  `Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset` object.

`Symfony\Bundle\AsseticBundle\Factory\AssetFactory` can not create `Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset` object.

Review please.

### CODE REVIEW

**Comment by hshn** [comment]
> The cause is that Symfony\Bundle\AsseticBundle\Factory\AssetFactory was creating Assetic\Asset\AssetReference object Instead of Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset object.
> 
> Symfony\Bundle\AsseticBundle\Factory\AssetFactory can not create Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset object.

You are right, but I think the `AssetReference` which is created by the `AssetFactory` references the `TemplateCacheAsset`.

Therefore, your solution looks like doing same things as the AssetReference does...
If the solution will resolve your issue, there may be causes related to AssetReference.

**Comment by ghost** [comment]
The `AssetReference` can not reference the TemplateCacheAsset, 
That's because the `AssetReference` does not find asset that must referred.

There are two ways to find asset that must referred.
- Getting by `AssetManager`
- Creating by `AssetFactory` (When `AssetManager` don't have the asset) 

## Getting by `AssetManager`

`assetic:watch` clear regularly all assets which `AssetManager` have.
https://github.com/symfony/assetic-bundle/blob/master/Command/WatchCommand.php#L72

So, it can not get the asset by `AssetManager`.

## Creating by `AssetFactory` (When `AssetManager` don't have the asset)

`AssetManager` have no feature to create `TemplateCacheAsset`.

Therefore, i think that `AssetReference` can not references `TemplateCacheAsset`

I also don't think that this is the best solution for the issue.
But I have no other good idea.

(In japanese)

`AssetReference` は `TemplateCacheAsset` を参照することが出来ません。
それはAssetReferenceが参照するべきAssetを見つけられないからです。

参照するべきAssetを見つける方法は２つあります。
- `AssetManager`から取得する
- `AssetFactory`で作成する（`AssetManager`にないとき）

### `AssetManager`から取得する

`assetic:watch`は定期的にAssetManagerの中のAssetオブジェクトをクリアします。
https://github.com/symfony/assetic-bundle/blob/master/Command/WatchCommand.php#L72

なので、`AssetManager`から取得することは出来ません。

### `AssetFactory`で作成する（`AssetManager`にないとき）

そもそも`AssetManager`に`TemplateCacheAsset`を作成する機能がありません。

ということで、最終的に

`AssetReference` は `TemplateCacheAsset` を参照することができない

ということになると思います。

これが最善策だとは思いませんが、他にいい方法も思いつかないです。

**Comment by hshn** [comment]
Sorry for delay.

AssetReference can reference TemplateCacheAsset because `symfony/assetic-bundle` has an ability to register any assets to AssetManager by tagging tag of `assetic.asset` and this bundle use the ability.

So the true cause of your issue is below you suggested:

> assetic:watch clear regularly all assets which AssetManager have.
> https://github.com/symfony/assetic-bundle/blob/master/Command/WatchCommand.php#L72
> 
> So, it can not get the asset by AssetManager.

Therefore, the way of your solution looks like out of this bundle scope. so I cannot merge it unfortunately.
Could you please apply it on your side?
Or please wait until the PR https://github.com/symfony/assetic-bundle/pull/412 which would resolve this issue is merged.

**Comment by ghost** [comment]
OK!
Your PR (https://github.com/symfony/assetic-bundle/pull/412) is good idea!
I wait until PR merged.

Thanks!

**Pull request closed without merging**
